// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TechAsset.Infrastructure.Data;

#nullable disable

namespace TechAsset.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260624025718_SeedEquipos")]
    partial class SeedEquipos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TechAsset.Domain.Entities.Equipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("categoria");

                    b.Property<string>("CodigoPatrimonial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_patrimonial");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Disponible")
                        .HasColumnName("estado");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("marca");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("CodigoPatrimonial")
                        .IsUnique();

                    b.ToTable("equipos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Categoria = "Laptops",
                            CodigoPatrimonial = "LAP-001",
                            Estado = "Disponible",
                            Marca = "Lenovo",
                            Nombre = "Laptop Lenovo ThinkPad L14"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Categoria = "Laptops",
                            CodigoPatrimonial = "LAP-002",
                            Estado = "Disponible",
                            Marca = "Dell",
                            Nombre = "Laptop Dell Latitude 5420"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Categoria = "Computadoras de escritorio",
                            CodigoPatrimonial = "PC-001",
                            Estado = "Disponible",
                            Marca = "HP",
                            Nombre = "Computadora HP ProDesk 600 G6"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Categoria = "Monitores",
                            CodigoPatrimonial = "MON-001",
                            Estado = "Disponible",
                            Marca = "LG",
                            Nombre = "Monitor LG UltraGear 24 pulgadas"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Categoria = "Impresoras",
                            CodigoPatrimonial = "IMP-001",
                            Estado = "Disponible",
                            Marca = "HP",
                            Nombre = "Impresora HP LaserJet Pro M404dn"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Categoria = "Tablets",
                            CodigoPatrimonial = "TAB-001",
                            Estado = "Disponible",
                            Marca = "Samsung",
                            Nombre = "Tablet Samsung Galaxy Tab S7"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Categoria = "Proyectores multimedia",
                            CodigoPatrimonial = "PRO-001",
                            Estado = "Mantenimiento",
                            Marca = "Epson",
                            Nombre = "Proyector Epson PowerLite X49"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Categoria = "Equipos de red",
                            CodigoPatrimonial = "NET-001",
                            Estado = "Disponible",
                            Marca = "Cisco",
                            Nombre = "Switch Cisco Catalyst 2960"
                        });
                });

            modelBuilder.Entity("TechAsset.Domain.Entities.Prestamo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EquipoId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipo_id");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_devolucion");

                    b.Property<DateTime>("FechaPrestamo")
                        .HasColumnType("date")
                        .HasColumnName("fecha_prestamo");

                    b.Property<string>("Observacion")
                        .HasColumnType("text")
                        .HasColumnName("observacion");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("prestamos", (string)null);
                });

            modelBuilder.Entity("TechAsset.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("area");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Colaborador")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Apellidos = "Admin",
                            Area = "Tecnología",
                            Correo = "admin@techasset.com",
                            Estado = true,
                            Nombres = "Juan",
                            PasswordHash = "$2a$11$S1xyiqsGkI5mSs97xOhroeNOjG4MhnXPPM5LhO9xKeYfQQTf9rk/C",
                            Rol = "Admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Apellidos = "Tecnico",
                            Area = "Tecnología",
                            Correo = "tecnico@techasset.com",
                            Estado = true,
                            Nombres = "Carlos",
                            PasswordHash = "$2a$11$S1xyiqsGkI5mSs97xOhroeNOjG4MhnXPPM5LhO9xKeYfQQTf9rk/C",
                            Rol = "Tecnico"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Apellidos = "Colaborador",
                            Area = "Recursos Humanos",
                            Correo = "colaborador@techasset.com",
                            Estado = true,
                            Nombres = "Maria",
                            PasswordHash = "$2a$11$S1xyiqsGkI5mSs97xOhroeNOjG4MhnXPPM5LhO9xKeYfQQTf9rk/C",
                            Rol = "Colaborador"
                        });
                });

            modelBuilder.Entity("TechAsset.Domain.Entities.Prestamo", b =>
                {
                    b.HasOne("TechAsset.Domain.Entities.Equipo", "Equipo")
                        .WithMany("Prestamos")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechAsset.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Prestamos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TechAsset.Domain.Entities.Equipo", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("TechAsset.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Prestamos");
                });
#pragma warning restore 612, 618
        }
    }
}
